"""Create tables 'account', 'shop', 'category', 'operation'

Revision ID: 176a411a8630
Revises: 
Create Date: 2021-09-14 16:05:02.817849

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '176a411a8630'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('email', sa.String(), nullable=False),
                    sa.Column('username', sa.String(), nullable=False),
                    sa.Column('password', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email'),
                    sa.UniqueConstraint('username')
                    )
    op.create_table('category',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('shop',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('operation',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('type', sa.Enum('BUY', 'SALE', name='typeoperation'), nullable=False),
                    sa.Column('date', sa.Date(), nullable=False),
                    sa.Column('shop_id', sa.Integer(), nullable=False),
                    sa.Column('category_id', sa.Integer(), nullable=True),
                    sa.Column('price', sa.Numeric(precision=18, scale=2), nullable=False),
                    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
                    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name='category_key', ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['shop_id'], ['shop.id'], name='shop_key', ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('operation')
    op.drop_table('shop')
    op.drop_table('category')
    op.drop_table('account')
    # ### end Alembic commands ###
