"""Add 'name' column for 'operation' table

Revision ID: 6d3b82f570ef
Revises: 176a411a8630
Create Date: 2021-09-15 12:41:07.772765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d3b82f570ef'
down_revision = '176a411a8630'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operation', sa.Column('name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('operation', 'name')
    # ### end Alembic commands ###
