"""Create tables 'account', 'shop', 'category', 'operation'

Revision ID: 8cf7aafec23c
Revises: 
Create Date: 2021-09-14 13:48:36.981574

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '8cf7aafec23c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
                    sa.Column('id', sa.Integer(), nullable=False, ),
                    sa.Column('email', sa.String(), nullable=False, unique=True),
                    sa.Column('username', sa.String(), nullable=False, unique=True),
                    sa.Column('password', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('category',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('operation',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('type', sa.Enum('BUY', 'SALE', name='type_operation'), nullable=False),
                    sa.Column('date', sa.Date(), nullable=False),
                    sa.Column('shop_id', sa.Integer(), nullable=False),
                    sa.Column('category_id', sa.Integer(), nullable=True),
                    sa.Column('price', sa.Numeric(precision=18, scale=2), nullable=False),
                    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('shop',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shop')
    op.drop_table('operation')
    op.drop_table('category')
    op.drop_table('account')
    # ### end Alembic commands ###
